readme_ver1
zangiro/app-plan pull request #1
Opened 2024-10-27 12:28 UTC by zangiro

概要
-
卒業制作 README

内容
-
新しくリポジトリを作成し、READMEを記述しました。
ご確認よろしくお願いします。

機能実装にて、卒業制作の時間的または不要な機能につき削ぎ落としたほうが良い機能。またはアプリ案の題材選びに難ありなどの問題点がございましたら遠慮なくお申し付けください。

2024-10-28 01:56 UTC, ippei-shimizu commented
対応ありがとうございます。以下の点に関してコメントします。
回答及びREADME.mdへの反映をお願いします。
...

ユーザーのアクションをできるだけシンプルにしている点はとても良いと思いましたが、診断後にグルメが表示されて詳細情報を見るだけでは、少しアプリとして物足りなさを感じてしまったので、グルメの詳細ページを見た後にユーザーが行いそうなアクションを考えた動線や機能を追加しても良いのかなと思いましたがいかがでしょうか？
（グルメの購入動線やお店の情報など...）

2024-10-31 14:11 UTC, zangiro commented
ご確認いただきありがとうございます。
ご指摘を受け、考察した結果まずユーザー層をより明確にするため、「料理より外食が好きな方」を追加しました。
それにともなってグルメ情報に興味を持ったユーザーが近隣の店舗情報を取得できるよう、google map APIの導入を行い、グルメの詳細ページで店舗情報を確認できる機能を考えました。
また別途で技術選定も記載いたしました。
お手数ですが再度ご確認お願いします。

---

「readme_ver2」　　　commit 030e1d1bb569b5d0f401a6c4ceb0294d8d161d86

2024-11-01 03:23 UTC, ippei-shimizu commented
対応ありがとうございます。以下の点に関してコメントします。
回答及びREADME.mdへの反映をお願いします。
...

- 診断後に表示されるグルメ情報のもととなるデータはどこから取得することを想定されていますか？また、診断結果が表示されるタイミングでは、お店の料理が表示されるイメージでしょうか？

2024-11-01 07:43 UTC, zangiro commented
ご確認いただきありがとうございます。

グルメ情報の初期データは利用規約に気をつけながら、農林水産省のサイト中心に拝借予定です。

以下、農林水産省サイトより
```
1  農林水産省Webサイトのコンテンツの利用について
農林水産省Webサイトで公開している情報(以下「コンテンツ」といいます。)は、どなたでも以下の1)～7)に従って、複製、公衆送信、翻訳・変形等の翻案等、自由に利用できます。商用利用も可能です。また、数値データ、簡単な表・グラフ等は著作権の対象ではありませんので、これらについては本利用ルールの適用はなく、自由に利用できます。
コンテンツ利用に当たっては、本利用ルールに同意したものとみなします。
```

加えてさらに情報を追加する場合も、利用規約で禁止されてないか確認しながら、画像の転載、文章の引用を行う予定です。

---

診断結果後の画像表示についてですが、特定の店舗のグルメ画像を表示するというよりも、レシピサイトで使われるようなテンプレ的な盛り付け例の画像を使う予定です。

そして詳細ページにて、そのグルメを提供している店舗情報をgoogle map APIを用いて表示しようと考えてます。

再度、ご確認よろしくお願いします。

2024-11-01 08:18 UTC, Tsuchiya2 commented
対応ありがとうございます。以下の点に関してコメントします。
回答及びREADME.mdへの反映をお願いします。
...

ゼロベースでREADME.md拝見しました。以下レビューになります。

■ターゲット
> おいしいものを食べるのが好きな方。
各地のグルメ情報に疎い方。
ネットをあっちこっち探すのが面倒な方。
料理より外食が好きな方。

上記ですが、上３つは、ほぼどの人にも当てはまるものかと思いました。「料理より外食が好きな方」というのがある程度絞り込んだターゲット層と記載されているかと思いますが、それでもやや漠然としすぎているように感じました。誰に向けたサービスなのかが分かる、ユーザー層をある程度絞り込むことで、そのユーザー層に訴求するサービスや機能が考えやすくなります。

■カテゴリ
診断系とのことですが、レビューやCGMなどへの展開まで考えられていますでしょうか？診断系はどうしても一度利用したら次は利用しないことが多く、ユーザーのフィードバックを受けながら継続的に開発が難しい傾向にあります。

■サービスの利用イメージ
> 価値：すくないポチ数で手軽にグルメ情報を得られる。
診断結果が基本画像のみなので、文字ありよりも素早く多くのグルメ情報を得られる。（文字は読まず見るだけなので）
得た知識から食欲、購買意欲を沸き立たせる。
得た知識から外出、遠出のきっかけづくりをする。
得た知識から、近隣に寄ったときの昼食、ディナー選びに助力したい。

上記ですが、診断系の場合、診断結果で出たものを覚えておくことも、近所に寄った際にその情報が想起できるかにも疑問を感じました。診断から実際にその場に行くための行動までを含めるなどしないと、1度きりで終わってしまわないかが気になりました。

■ サービスの差別化ポイント・推しポイント
> 既存のサービスは正確性や利便性がある分、文字や操作パネルが多くなり、一度に画面内に表示できる検索情報の画像の最大量はそんなに多くないのに対し、自分のアプリはとにかく視覚情報優先でページ（画面）いっぱいにグルメ情報を表示できるようにしたいです。

↑画像の表示料を多くするとありますが、具体的に何枚の画像を表示する予定でしょうか？README.mdに詳しく記載してください。枚数によっては他のサービスの方が多く表示されるもしくはスクロールすることで無限に近い数表示されるなどあるかと思うので、それらと比較してどのくらいの枚数の画像を表示させる予定なのかが気になりました。

> 既存サービスは正確な情報が調べられる分、必然的にポチ数が多くなってしまうと思います（条件Aを設定したあと、条件Bの設定は？条件Cの設定は？みたいに）。
自分のアプリは利便性を落とす代わりに、少ないポチ数で得たいグルメの情報を得られるようにしたいです。（極力選択肢を減らす）

↑「...少ないポチ数で得たいグルメの情報を得られるようにしたいです。...」とありますが、願望や希望で終わってしまっているように読みました。具体的に何アクションでグルメ情報に辿り着けるのか、それは他のサービスと比較して、どれくらい少ないのかを詳しくREADME.mdに記載してください。

> 画像検索だと関係ない画像が結構ヒットしてしまいますが、選んだタグに関係ある物のみを表示して一度に視野・ウィンドウにて得られる情報を多くしたいです。

↑こちらも願望・希望で終わっています。他のサービスと比較して具体的にどういうところが異なるのかが分かるようにREADME.mdに詳しい説明を記載してください。

2024-11-01 12:12 UTC, zangiro commented
ご確認ありがとうございます。

こちらに変更を記述しました。
「readme_ver3」　commit db6fee254e1f4ae66e0c123c3adc18dbf7f62825

ご指摘を受け以下を変更いたしました。
・ユーザー層をより明確に。
・1度きりの使用で終わらないよう利用イメージを改良。
・他サービスと比べ、本サービスの推しポイント・差分点をより明確にしつつ、いまいちな差分点のカットを行う。

お手数ですが、最後ご確認お願いします。

2024-11-02 06:45 UTC, tarakish requested changes
修正確認しました。
初期段階でユーザーに使ってもらうためにある程度データが登録されている必要があるかと思いますが、こちらはどのように用意するか考えている事があれば記載をお願いします！

2024-11-02 07:05 UTC, zangiro commented
ご確認いただきありがとうございます。

前述にありますが、グルメ情報の初期データは利用規約に気をつけながら、農林水産省のサイト中心に拝借予定です。

以下、農林水産省サイトより
```
1  農林水産省Webサイトのコンテンツの利用について
農林水産省Webサイトで公開している情報(以下「コンテンツ」といいます。)は、どなたでも以下の1)～7)に従って、複製、公衆送信、翻訳・変形等の翻案等、自由に利用できます。商用利用も可能です。また、数値データ、簡単な表・グラフ等は著作権の対象ではありませんので、これらについては本利用ルールの適用はなく、自由に利用できます。
コンテンツ利用に当たっては、本利用ルールに同意したものとみなします。
```

グルメ情報の基礎となるデータは「メイン画像、別アングル画像（あれば）、短い紹介文（index用）、長めの紹介文（show）」のみとなっておりデータ追加の労力はそこまで高くないため、最低限サービスが成立するための、おおよその情報は自ら調達する予定です。

投稿も比較的簡単にできるようにし、mattermostなどでお願いし、気が向いた方に投稿も手伝ってもらったらなと考えてます。

お手数ですが、再度ご確認お願いします。

2024-11-05 03:14 UTC, tmtkzk0823 commented
上記確認しました！
LGTMです！

2024-11-05 03:19 UTC, zangiro commented
ご確認ありがとうございます。
マージさせていただきます。

2024-11-05 03:24 UTC, merged